/**
 * Assert the JS geometry mirror against vectors generated by the Rust crate.
 *
 * `src/coordinates.js` duplicates math that `omniphony-geometry` owns. That
 * duplication is deliberate — per-frame Three.js work stays in the browser at
 * zero integration cost (the alternative, WASM, is a documented follow-up) —
 * but a mirror only stays honest if something checks it. So the crate dumps its
 * answers and this replays every one through the JS.
 *
 * Regenerate the vectors after any change to the geometry:
 *
 *   cd ../omniphony-renderer && cargo run -p omniphony-geometry \
 *     --example dump_golden_vectors > ../omniphony-studio/scripts/golden/geometry.json
 *
 * Run with `npm run test:math`.
 *
 * Note the axis order: the crate speaks ADM (x right, y front, z up), the JS
 * speaks Three.js scene (x depth, y up, z right). Every case below converts
 * explicitly with the same swizzle the crate documents — the whole point being
 * that reordering components by hand is what caused the frame bug in the first
 * place.
 */

import { readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import {
  cartesianToSpherical,
  sphericalToCartesianDeg,
  omniphonyToSceneCartesian,
  sceneToOmniphonyCartesian,
  depthWarpWithRatios,
  inverseMapRoomDepth,
  normalizeAngleDeg,
  snapAngleDeg,
  normalizedOmniphonyToScenePosition,
  scenePositionToNormalizedOmniphony
} from '../src/coordinates.js';
import { app } from '../src/state.js';

const here = dirname(fileURLToPath(import.meta.url));
const golden = JSON.parse(readFileSync(join(here, 'golden', 'geometry.json'), 'utf8'));

// Far tighter than any UI-meaningful precision (~0.01), loose enough to absorb
// the last bits of a 28-iteration bisection (~1.9e-9) and the frontend's
// cardinal snapping (1e-5 window, but only onto values the crate also lands on).
const TOLERANCE = 1e-6;

let checked = 0;
const failures = [];

function close(actual, expected, label) {
  checked += 1;
  const a = Number(actual);
  if (!Number.isFinite(a) || Math.abs(a - expected) > TOLERANCE) {
    failures.push(`${label}: expected ${expected}, got ${actual}`);
  }
}

function closeTriple(actual, expected, label) {
  close(actual[0], expected[0], `${label}.x`);
  close(actual[1], expected[1], `${label}.y`);
  close(actual[2], expected[2], `${label}.z`);
}

/** Point the shared room state at one golden room configuration. */
function useRoom({ ratio, rear, lower, blend }) {
  app.roomRatio.width = ratio[0];
  app.roomRatio.length = ratio[1];
  app.roomRatio.height = ratio[2];
  app.roomRatio.rear = rear;
  app.roomRatio.lower = lower;
  app.roomRatio.centerBlend = blend;
}

// ── Cartesian -> spherical ───────────────────────────────────────────────────
for (const c of golden.toSpherical) {
  const [x, y, z] = c.adm;
  const scene = omniphonyToSceneCartesian({ x, y, z });
  const got = cartesianToSpherical(scene);
  const label = `toSpherical(${c.adm})`;
  // Azimuth is undefined on the vertical axis: any value points the same way,
  // so the crate and JS are both free to return 0 there. Skip rather than
  // pretend the comparison means something.
  if (Math.abs(c.el) < 90 - 1e-9) {
    close(got.az, c.az, `${label}.az`);
  }
  close(got.el, c.el, `${label}.el`);
  close(got.dist, c.dist, `${label}.dist`);
}

// ── Spherical -> cartesian ───────────────────────────────────────────────────
for (const c of golden.fromSpherical) {
  const scene = sphericalToCartesianDeg(c.az, c.el, c.dist);
  const adm = sceneToOmniphonyCartesian(scene);
  closeTriple([adm.x, adm.y, adm.z], c.adm, `fromSpherical(${c.az}, ${c.el}, ${c.dist})`);
}

// ── Depth warp and its inverse ───────────────────────────────────────────────
for (const c of golden.mapDepth) {
  const label = `mapDepth(${c.depth}, front=${c.front}, rear=${c.rear}, blend=${c.blend})`;
  close(depthWarpWithRatios(c.depth, c.front, c.rear, c.blend), c.mapped, label);

  // inverseMapRoomDepth reads the shared room state rather than taking ratios.
  app.roomRatio.length = c.front;
  app.roomRatio.rear = c.rear;
  app.roomRatio.centerBlend = c.blend;
  close(inverseMapRoomDepth(c.mapped), c.inverse, `inverse${label}`);
}

// ── Angle helpers ────────────────────────────────────────────────────────────
for (const c of golden.normalizeDeg) {
  close(normalizeAngleDeg(c.in), c.out, `normalizeAngleDeg(${c.in})`);
}
for (const c of golden.snapDeg) {
  close(snapAngleDeg(c.angle, c.step, c.threshold), c.out, `snapAngleDeg(${c.angle})`);
}

// ── Room scaling, both directions ────────────────────────────────────────────
for (const c of golden.roomScaledPosition) {
  useRoom(c);
  const [x, y, z] = c.adm;
  const label = `roomScaled(${c.adm}, ratio=${c.ratio})`;

  // The crate returns room-scaled ADM; the JS returns it already swizzled to
  // scene order.
  const scene = normalizedOmniphonyToScenePosition({ x, y, z });
  const expectedScene = [c.scaled[1], c.scaled[2], c.scaled[0]];
  closeTriple([scene.x, scene.y, scene.z], expectedScene, label);

  const back = scenePositionToNormalizedOmniphony(scene);
  closeTriple([back.x, back.y, back.z], c.inverse, `inverse${label}`);
}

// ── Report ───────────────────────────────────────────────────────────────────
if (failures.length > 0) {
  console.error(`FAIL — ${failures.length} of ${checked} assertions disagree with the Rust crate:\n`);
  for (const f of failures.slice(0, 25)) {
    console.error(`  ${f}`);
  }
  if (failures.length > 25) {
    console.error(`  … and ${failures.length - 25} more`);
  }
  console.error('\nIf the geometry changed on purpose, regenerate the vectors (see the header).');
  process.exit(1);
}

console.log(`ok — ${checked} assertions match omniphony-geometry`);
