[package]
name = "audio_input"
version = "0.2.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
audio_output.workspace = true
diag.workspace = true
libc.workspace = true
log.workspace = true
renderer.workspace = true
serde.workspace = true
spdif.workspace = true
sys.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
pipewire.workspace = true
